services:
  - type: web
    name: qalia-github-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GITHUB_APP_ID
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DEFAULT_DEPLOY_URL
        value: "https://{repo}.herokuapp.com"
        sync: false
      - key: MAX_ANALYSIS_TIMEOUT
        value: "600"
        sync: false
      - key: MAX_EXPLORATION_DEPTH
        value: "3"
        sync: false
      - key: DEFAULT_FRAMEWORKS
        value: "playwright,cypress,jest"
        sync: false
      - key: ENABLE_PR_COMMENTS
        value: "true"
        sync: false
      - key: ENABLE_CHECK_RUNS
        value: "true"
        sync: false 