name: QA AI - Dependency & Import Test

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout QA AI Source
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Test Dependency Installation
      run: |
        echo "🔧 Testing QA AI dependency installation..."
        pip install --no-cache-dir -r requirements.txt
        
    - name: Install Playwright Browser
      run: |
        echo "🌐 Installing Playwright browser for QA AI..."
        playwright install chromium
        
    - name: Test QA AI Module Imports
      run: |
        echo "📦 Testing QA AI module imports..."
          python3 -c "
          import sys
          sys.path.insert(0, '.')
        
        print('Testing QA AI imports...')
        try:
            import main
            print('✅ main.py imported successfully')
        except Exception as e:
            print('❌ main.py import error:', e)
            sys.exit(1)
        
          try:
              from scripts.run_exploration import run_exploration
              print('✅ run_exploration imported successfully')
          except Exception as e:
            print('❌ run_exploration import error:', e)
            sys.exit(1)
          
          try:
              from generators import TestCaseGenerator
              print('✅ TestCaseGenerator imported successfully')
          except Exception as e:
            print('❌ TestCaseGenerator import error:', e)
            sys.exit(1)
        
        print('🎉 All QA AI imports successful!')
        "
        
    - name: Test QA AI Help Command
      run: |
        echo "❓ Testing QA AI help command..."
        python main.py --help || echo "Help command test completed" 